# These are supported funding model platforms

github: spacehuhntech
patreon: #
open_collective: # Replace with a single Open Collective username
ko_fi: spacehuhn
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: #
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['spacehuhn.com/store/']
