name: Check version numbers on release

on:
  push:
    tags:
      - '*'

jobs:
  version-check:
    name: "Check version number"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Print versions
        run: | 
          echo "Release tag: $GITHUB_REF/refs\/tags\//}"
          echo "src/SimpleCLI.h: $(grep -E "SIMPLECLI_VERSION \"[0-9]?.[0-9]?.[0-9]?\"$" src/SimpleCLI.h | grep -oE "[0-9]?\.[0-9]?\.[0-9]?")"
          echo "library.json: $(grep -E "\"version\": \"[0-9]?.[0-9]?.[0-9]?\",$" library.json | grep -oE "[0-9]?\.[0-9]?\.[0-9]?")"
          echo "library.properties: $(grep -E "version=[0-9]?.[0-9]?.[0-9]?$" library.properties | grep -oE "[0-9]?\.[0-9]?\.[0-9]?")"
          
#      - name: Delete latest Release
#        if: env.RELEASE_VERSION != env.SOURCE_VERSION || env.RELEASE_VERSION != env.JSON_VERSION || env.RELEASE_VERSION != env.PROPERTIES_VERSION
#        uses: ame-yu/action-delete-latest-release@v2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Fail job
        if: env.RELEASE_VERSION != env.SOURCE_VERSION || env.RELEASE_VERSION != env.JSON_VERSION || env.RELEASE_VERSION != env.PROPERTIES_VERSION
        run: exit 1
